name: flutter_ijkplayer
description: Base by bilibili ijkplayer, it's video/audio player, support https、rtmp、m3u8 and more protocol.
version: 1.0.0
author: peter<maxu@100tal.com>
homepage: https://github.com/CaiJingLong/flutter_ijkplayer
publish_to: http://47.92.66.57:8282/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: top.kikt.ijkplayer
    pluginClass: IjkplayerPlugin
